### PR TITLE
TEL-137/Temporary-fix-for-faults-component

### PR DESCRIPTION
**Pull request by burtonjong**
I found the root of all the rerendering - it is in two files (i found the problem in `SocketContextProvider.tsx` , still looking for the one in `_app.tsx`)

image

By removing `SocketContextProvider.tsx` and `LoadingWrapper.tsx` the site no longer rerenders like crazy

You can isolate the issue in `SocketContextProvider.tsx` by putting it back in `_app.tsx`. The main problem is this use effect and function call:

image

By deleting this you can see that it no longer rerenders. I assume its the interval that is causing this

### CODE REVIEW

**Comment by burtonjong** [comment]
I found the root of all the rerendering - it is in two files

image

By removing `SocketContextProvider.tsx` and `LoadingWrapper.tsx` the site no longer rerenders like crazy

You can isolate the issue in `SocketContextProvider.tsx` by putting it back in `_app.tsx`. The main problem is this use effect and function call:

image

By deleting this you can see that it no longer rerenders. I assume its the interval that is causing this

**Review by justin-phxm — APPROVED** [review]

**Review by David-Rodriguez-Barrios — APPROVED** [review]
Looks good! 💯

**Review by kr1s-r — APPROVED** [review]
LGTM

**Comment by ideen1** [comment]
One thing I've noticed is that this PR caused a regression in connecting to AWS. I know it fixed the pre-render issue but did it somehow replace the socket connection functionality? We don't import the SocketContext anymore

**Comment by burtonjong** [comment]
@ideen1 similar to how the faults context only wraps the components that use the context, a fix (temporary i guess) was to so the same and move the socketcontext down to only the one component thats uses it (which is the component near the logo)

**Comment by burtonjong** [comment]
If the problem was this PR, then it would be in StatusComponent.tsx

**Pull request merged**
