### PR TITLE
Graph modals cool2

### PR DESCRIPTION
**Pull request by justin-phxm**

### CODE REVIEW

**Review by brian-ngyn — APPROVED** [review]
LGTM

**Comment by ideen1** [comment]
Looks awesome few things we need to finish before it goes in:

1. Right now you can drag graphs outside of the Frame of the website, make sure it doesn't let you drag outside of the screen.
2. Make cursor turn into a "move crosshair" when you hover over the top of the graph component.
3. The entire top of the Graph Div should be something you can drag. Maybe even the whole div.
4. Can you make the boxes smaller, I'm thinking about 50% of the size they currently are.
5. Can you make the graph use real data from the parameter that opened it? It should show data for the last 20 seconds or something. A useState that you use as a buffer should work for this.
6. Can you remove the "G" and make it so when you hover on any parameter a pop up comes up showing "Open Graph"

**Comment by justin-phxm** [comment]
> Looks awesome few things we need to finish before it goes in:
> 
> 1. Right now you can drag graphs outside of the Frame of the website, make sure it doesn't let you drag outside of the screen.
> 2. Make cursor turn into a "move crosshair" when you hover over the top of the graph component.
> 3. The entire top of the Graph Div should be something you can drag. Maybe even the whole div.
> 4. Can you make the boxes smaller, I'm thinking about 50% of the size they currently are.
> 5. Can you make the graph use real data from the parameter that opened it? It should show data for the last 20 seconds or something. A useState that you use as a buffer should work for this. - Separate Ticket
> 6. Can you remove the "G" and make it so when you hover on any parameter a pop up comes up showing "Open Graph"
> 7. Move the DraggableGraph component into molecules.
> 8. The logic inside of the GraphContainer should be moved to the Graph context.
> 9. Make the Graph Div go into dark mode when the site changes to dark mode - I did this

1. Finished
2. Finished
3. Finished
4. Ideen done this
5. Separate ticket
6. Finished
7. Finished
8. I'm not sure what this means

**Review by ideen1 — COMMENTED** [review]
We will merge this in with #82 instead.

**Comment by ideen1** [comment]
> We will merge this in with #82 instead.

**Pull request closed without merging**
