### PR TITLE
mobile view fixed

### PR DESCRIPTION
**Pull request by burtonjong**
Only thing is the ScrollContainer which doesnt really "scroll" in mobile view but it's part of a library so not to sure how it works

### CODE REVIEW

**Review by ideen1 — DISMISSED** [review]
Looks good to me!

**Review by justin-phxm — APPROVED** [review]
LGTM, just need to fix the scroll

**Review by alexwhelan12 — DISMISSED** [review]
Looks good to me!

**Review by justin-phxm — DISMISSED** [review]

**Review by ideen1 — APPROVED** [review]
LGTM!!1

**Review by justin-phxm — APPROVED** [review]

**Pull request merged**
