### PR TITLE
Tel 95 make graph component to be used in different places

### PR DESCRIPTION
**Pull request by ideen1**

### CODE REVIEW

**Review by justin-phxm — DISMISSED** [review]
Looks good to me

**Review by justin-phxm — APPROVED** [review]
1. Freezes when you switch tabs
2. Does not support T/F or Text fields
3.

**Review by justin-phxm — APPROVED** [review]
ok!

**Review by alexwhelan12 — COMMENTED** [review]
Looks good to me!

**Review by alexwhelan12 — COMMENTED** [review]
Looks awesome!

**Review by justin-phxm — APPROVED** [review]
plz

**Review by alexwhelan12 — APPROVED** [review]
Looks great!

**Pull request merged**
